spring:
  datasource:
    url: jdbc:mysql://sparcle.mysql.database.azure.com:3306/precapstone_spakle_be
    username: sparcle
    password: heca704!!
    hikari:
      connection-timeout: 15000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug